/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package db4o;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class vista extends javax.swing.JFrame {

    /**
     * Creates new form vista
     */
    String tituloCancion;
    
    facadeCantante fc = new facadeCantante();
    facadeCancion fCancion = new facadeCancion();
    
    public vista() {
        initComponents();
        setLocationRelativeTo(null);
        tablaCantantes.setModel(fc.getCantantes());   
        tablaCanciones.setModel(fCancion.getCanciones());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaCantantes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCantanteNombre = new javax.swing.JTextField();
        txtCantanteEstilo = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btnCantanteNuevo = new javax.swing.JButton();
        btnCantanteEliminar = new javax.swing.JButton();
        btnCantanteModificar = new javax.swing.JButton();
        btnCantanteGuardar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtCancionTitulo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCancionDuracion = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        btnCancionNuevo = new javax.swing.JButton();
        btnCancionEliminar = new javax.swing.JButton();
        btnCancionModificar = new javax.swing.JButton();
        btnCancionGuardar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaCanciones = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtCancionCantante = new javax.swing.JTextField();
        btnCancionBuscarCantante = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Cantantes"));

        tablaCantantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Estilo"
            }
        ));
        tablaCantantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaCantantesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaCantantes);

        jLabel1.setText("Nombre: ");

        jLabel2.setText("Estilo: ");

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnCantanteNuevo.setText("Nuevo");

        btnCantanteEliminar.setText("Eliminar");
        btnCantanteEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCantanteEliminarActionPerformed(evt);
            }
        });

        btnCantanteModificar.setText("Modificar");
        btnCantanteModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCantanteModificarActionPerformed(evt);
            }
        });

        btnCantanteGuardar.setText("Guardar");
        btnCantanteGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCantanteGuardarMouseClicked(evt);
            }
        });
        btnCantanteGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCantanteGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCantanteNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCantanteGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(btnCantanteModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCantanteEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCantanteNuevo)
                    .addComponent(btnCantanteEliminar)
                    .addComponent(btnCantanteModificar)
                    .addComponent(btnCantanteGuardar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCantanteNombre)
                            .addComponent(txtCantanteEstilo))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCantanteNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCantanteEstilo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Canciones"));
        jPanel3.setPreferredSize(new java.awt.Dimension(460, 535));

        jLabel3.setText("Titulo:");

        jLabel4.setText("Duracion:");

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnCancionNuevo.setText("Nuevo");

        btnCancionEliminar.setText("Eliminar");
        btnCancionEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancionEliminarActionPerformed(evt);
            }
        });

        btnCancionModificar.setText("Modificar");
        btnCancionModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancionModificarActionPerformed(evt);
            }
        });

        btnCancionGuardar.setText("Guardar");
        btnCancionGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancionGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCancionNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCancionGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(btnCancionModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCancionEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancionNuevo)
                    .addComponent(btnCancionEliminar)
                    .addComponent(btnCancionModificar)
                    .addComponent(btnCancionGuardar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tablaCanciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Título", "Cantante", "Duración"
            }
        ));
        tablaCanciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaCancionesMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tablaCanciones);

        jLabel5.setText("Cantante:");

        btnCancionBuscarCantante.setText("Search");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCancionCantante)
                            .addComponent(txtCancionTitulo))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCancionDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnCancionBuscarCantante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCancionCantante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancionBuscarCantante))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCancionDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtCancionTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Biblioteca Multimedia"));

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cancion", "Cantante", "Estilo", "Duracion"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        jLabel6.setText("Introduce Cantante: ");

        jLabel7.setText("Introduce Duración: ");

        jLabel8.setText("-");

        jButton10.setText("Search");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jButton10))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCantanteGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCantanteGuardarActionPerformed
        //Boton Guardar Cantante
        String nombre = txtCantanteNombre.getText();
        String estilo = txtCantanteEstilo.getText();
        boolean comp = false;
        int fila = tablaCantantes.getRowCount();
        
        for(int i=0; i<fila; i++){
                    String nom = String.valueOf(tablaCantantes.getValueAt(i, 0));
                    
                    if(nom.equalsIgnoreCase(nombre)){
                        comp = true;
                    }
        }
        
        if(comp){
            JOptionPane.showMessageDialog(null, "El cantante ya existe");
        }else{
            fc.añadirCantante(nombre, estilo);
        
            tablaCantantes.setModel(fc.getCantantes());
        }
        
    }//GEN-LAST:event_btnCantanteGuardarActionPerformed

    private void btnCantanteGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCantanteGuardarMouseClicked
        
    }//GEN-LAST:event_btnCantanteGuardarMouseClicked

    private void tablaCantantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaCantantesMouseClicked
        //Tabla cantantes
        String nombre = "";
        String estilo = "";
        
        
        int fila;
        
        fila = this.tablaCantantes.rowAtPoint(evt.getPoint());
            if (fila > -1){                
               nombre = ( String.valueOf( this.tablaCantantes.getValueAt(fila, 0) ));
               estilo = ( String.valueOf( this.tablaCantantes.getValueAt(fila, 1) ));
            }
            
            txtCantanteNombre.setText(nombre);
            txtCantanteEstilo.setText(estilo);
    }//GEN-LAST:event_tablaCantantesMouseClicked

    private void btnCantanteModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCantanteModificarActionPerformed
        //Boton modificar cantante
        String nombre = txtCantanteNombre.getText();
        String estilo = txtCantanteEstilo.getText();
        
        if(txtCantanteNombre.getText().isEmpty() || txtCantanteEstilo.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Rellena todos los campos");
        }else{
            fc.modificarCantante(nombre, estilo);
            tablaCantantes.setModel(fc.getCantantes());
        }
        
    }//GEN-LAST:event_btnCantanteModificarActionPerformed

    private void btnCantanteEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCantanteEliminarActionPerformed
        //Boton eliminar cantante
        String nombre = txtCantanteNombre.getText();
        
        if(txtCantanteNombre.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Indica el nombre del cantante que desea borrar");
        }else{
            fc.eliminarCantante(nombre);
            tablaCantantes.setModel(fc.getCantantes());
        }
    }//GEN-LAST:event_btnCantanteEliminarActionPerformed

    private void btnCancionGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancionGuardarActionPerformed
        //Boton Guardar Cancion
        String nomCantante = txtCancionCantante.getText();
        String titulo = txtCancionTitulo.getText();
        String duracion = txtCancionDuracion.getText();
        
        boolean comp = false;
        int fila = tablaCanciones.getRowCount();
        
        for(int i=0; i<fila; i++){
                    String nom = String.valueOf(tablaCanciones.getValueAt(i, 0));
                    
                    if(nom.equalsIgnoreCase(titulo)){
                        comp = true;
                    }
        }
        
        if(comp){
            JOptionPane.showMessageDialog(null, "La cancion ya existe");
        }else{
            fCancion.añadirCancion(titulo, nomCantante, duracion);
        
            tablaCanciones.setModel(fCancion.getCanciones());
        }
    }//GEN-LAST:event_btnCancionGuardarActionPerformed

    private void btnCancionModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancionModificarActionPerformed
        //Boton modificar cancion
        String titulo = txtCancionTitulo.getText();
        String nomCantante = txtCancionCantante.getText();
        String duracion = txtCancionDuracion.getText();
        
        if(txtCancionTitulo.getText().isEmpty() || txtCancionCantante.getText().isEmpty() || txtCancionDuracion.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Rellena todos los campos");
        }else{
            fCancion.modificarCancion(tituloCancion, titulo, nomCantante, duracion);
            tablaCanciones.setModel(fCancion.getCanciones());
        }
    }//GEN-LAST:event_btnCancionModificarActionPerformed

    private void tablaCancionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaCancionesMouseClicked
        //Tabla canciones
        
        String nomCantante = "";
        String duracion = "";
        
        
        int fila;
        
        fila = this.tablaCanciones.rowAtPoint(evt.getPoint());
            if (fila > -1){                
               tituloCancion = ( String.valueOf( this.tablaCanciones.getValueAt(fila, 0) ));
               duracion = ( String.valueOf( this.tablaCanciones.getValueAt(fila, 1) ));
               nomCantante = ( String.valueOf( this.tablaCanciones.getValueAt(fila, 2) ));
            }
            
            txtCancionTitulo.setText(tituloCancion);
            txtCancionDuracion.setText(duracion);
            txtCancionCantante.setText(nomCantante);
    }//GEN-LAST:event_tablaCancionesMouseClicked

    private void btnCancionEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancionEliminarActionPerformed
        //Boton eliminar cantante
        String nombre = txtCantanteNombre.getText();
        
        if(txtCantanteNombre.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Indica el nombre de la cancion que desea borrar");
        }else{
            fc.eliminarCantante(nombre);
            tablaCantantes.setModel(fc.getCantantes());
        }
    }//GEN-LAST:event_btnCancionEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancionBuscarCantante;
    private javax.swing.JButton btnCancionEliminar;
    private javax.swing.JButton btnCancionGuardar;
    private javax.swing.JButton btnCancionModificar;
    private javax.swing.JButton btnCancionNuevo;
    private javax.swing.JButton btnCantanteEliminar;
    private javax.swing.JButton btnCantanteGuardar;
    private javax.swing.JButton btnCantanteModificar;
    private javax.swing.JButton btnCantanteNuevo;
    private javax.swing.JButton jButton10;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTable tablaCanciones;
    private javax.swing.JTable tablaCantantes;
    private javax.swing.JTextField txtCancionCantante;
    private javax.swing.JTextField txtCancionDuracion;
    private javax.swing.JTextField txtCancionTitulo;
    private javax.swing.JTextField txtCantanteEstilo;
    private javax.swing.JTextField txtCantanteNombre;
    // End of variables declaration//GEN-END:variables
}
